
<div class="other">
	<dl class="clearfix">
		<dt>承办方</dt>
		<dd class="gtv"><a target="_blank" href="http://www.gtv.com.cn"><img src="http://ossweb-img.qq.com/images/cf/cfpl/gtv-logo.jpg?d=0314" width="117" height="46" alt="gtv" /></a></dd>
		<dt >合作媒体</dt>
		<dd  class="media">
		<a target="_blank" class="pk52" href="http://cf.52pk.com"><img src="http://ossweb-img.qq.com/images/cf/cfpl/52pk-logo.jpg"width="117" height="46" alt="52pk" /></a> 
		<a target="_blank" class="aipai" href="http://cf.aipai.com/"><img src="http://ossweb-img.qq.com/images/cf/cfpl/aipai-logo.jpg?d=0314" width="117" height="46" alt="爱拍" /></a> 
		<a target="_blank" href="http://www.766.com"><img src="http://ossweb-img.qq.com/images/cf/cfpl/766-logo.jpg?d=0314" width="117" height="46" alt="766" /></a> 
		<a target="_blank" class="ku6" href="http://games.ku6.com"><img src="http://ossweb-img.qq.com/images/cf/cfpl/ku6-logo.jpg?d=0314" width="117" height="46" alt="酷6" /></a> 
		<a target="_blank" class="g17173" href="http://www.17173.com/"><img src="http://ossweb-img.qq.com/images/cf/cfpl/17173-logo.jpg?d=0314" width="117" height="46" alt="17173" /></a> 
		<a target="_blank" class="pptv" href="http://www.pptv.com/"><img src="http://ossweb-img.qq.com/images/cf/cfpl/pptv-logo.jpg" width="117" height="46" alt="pptv" /></a> 
		<a target="_blank" class="tudou" href="http://www.tudou.com/"><img src="http://ossweb-img.qq.com/images/cf/cfpl/tudou-logo.jpg" width="117" height="46" alt="tudou" /></a> 
		<a target="_blank" class="pcgames" href="http://www.pcgames.com.cn/"><img src="http://ossweb-img.qq.com/images/cf/cfpl/pcgames-logo.jpg" width="117" height="46" alt="pcgames" /></a> 
		</dd>
	</dl>
</div>