	<h1 class="htxt"><strong>CFPL</strong>2011穿越火线全国职业联赛</h1>
	<p class="htxt">全程网络直播 单赛季总奖金<em>1000000RMB</em></p>
	<div class="header">
		<div class="top">
			<ul class="quicklink clearfix">
				<li><a href="http://cf.qq.com/web201105/download.shtml" target="_blank">下载游戏</a></li>
				<li><a href="http://cf.qq.com/brand_2011/" target="_blank">CF品牌站</a></li>
				<li><a href="http://cf.qq.com/main.shtml" target="_blank">CF官网</a></li>
			</ul>
			<div class="share clearfix">
				<a href="javascript:void(0);" onclick="postToWb();return false;" class="tmblog">分享到腾讯微博</a>
				<a href="javascript:void(0);"  onclick="window.open('http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url='+encodeURIComponent('http://cf.qq.com/cfpl/index.shtml'));return false;" title="分享到QQ空间">分享到QQ空间</a>
			</div>
		</div>
		<div class="nav">
			<ul class="menu">
				<li><a href="./index.shtml" class="homelink">首页</a></li>
				<li class="go"><a href="http://cf.qq.com/cfpl/guess.shtml"><span>竞猜大厅</span></a></li>
				<li id="menuListSel03"><a href="http://cf.qq.com/cfpl/video.shtml"  target="_blank" class="go"><span>直播大厅</span></a></li>
				<li id="menuListSel01"><a href="http://cf.qq.com/cfpl/process.shtml">赛事信息</a></li>
				<li id="menuListSel02"><a href="http://cf.qq.com/cfpl/database.shtml">数据库</a></li>
				
				<li><a href="http://cf.qq.com/main.shtml" target="_blank" class="end">官网</a></li>
			</ul>
			<div class="submenuwrap" id="subMenuList01">
					<div class="filter"></div>
					<ul class="submenu">
						<li><a href="http://cf.qq.com/cfpl/rule.shtml">&gt;&nbsp;比赛规则</a></li>
						<li><a href="http://cf.qq.com/cfpl/process.shtml">&gt;&nbsp;赛程安排</a></li>
						<li><a href="http://cf.qq.com/cfpl/site.shtml">&gt;&nbsp;场地介绍</a></li>
					</ul> 
			</div>
<!-- 			<div class="submenuwrap" id="subMenuList02">
					<div class="filter"></div>
					<ul class="submenu">
						<li><a href="javascript:void(0)" onclick="alert('暂未开放,敬请期待!')">&gt;&nbsp;战队资料</a></li>
						<li><a href="javascript:void(0)" onclick="alert('暂未开放,敬请期待!')">&gt;&nbsp;选手资料</a></li>
						<li><a href="javascript:void(0)" onclick="alert('暂未开放,敬请期待!')">&gt;&nbsp;联赛赛程</a></li>
					</ul> 
			</div> -->
			<div class="submenuwrap" id="subMenuList03">
					<div class="filter"></div>
					<ul class="submenu">
						<li><a href="http://cf.qq.com/cfpl/video.shtml" target="_blank">&gt;&nbsp;直播大厅</a></li>
						<li><a href="http://cf.766.com/cfpl2011/video/index.shtml" target="_blank">&gt;&nbsp;比赛视频</a></li>
						<li><a href="http://cf.766.com/demo" target="_blank">&gt;&nbsp;REP下载</a></li>
                         <li><a href="http://cf.qq.com/cfpl/propagate.shtml" >&gt;&nbsp;宣传片欣赏</a></li>
					</ul> 
			</div>
		</div>
	</div>