	<div class="header">
		<a href="http://x5.qq.com/main.shtml" class="logo ht" target="_blank" title="QQ炫舞">QQ炫舞</a>
		<a href="http://x5.qq.com/act/a201200428zhe/" class="logo4 ht" target="_blank" title="4周年">4周年</a>
		<a href="http://x5.qq.com/act/a20120520love/" class="logoC ht" target="_blank" title="触动心&middot;触动爱">触动心&middot;触动爱</a>
		<h1 class="hidden" id="h1">浪漫四周年 小镇游园狂欢季开启</h1>
		<p class="hidden">2012年5月9日</p>
		<div class="top_nav">
			<span class="hidden">分享到：</span><a href="javascript:postToWb();" class="ico_qt ht" title="分享到腾讯微博">分享到腾讯微博</a><a href="###" onclick="javascript:window.open('http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=' + tloca);return false;" class="ico_qz ht" title="分享到QQ空间">分享到QQ空间</a><a href="http://x5.qq.com/main.shtml" class="top_link ht" target="_blank" title="炫舞官网">炫舞官网</a><a href="http://x5.qq.com/web201011/download.shtml" class="top_link2 ht" target="_blank" title="下载炫舞">下载炫舞</a>
		<script type="text/javascript">edit();</script>
		</div>
		<!--a href="javascript:DivShow1();" class="header_a ht" title="版本视频点击查看">版本视频点击查看</a-->
	</div>
	<ul class="main_nav c" id="main_nav">
		<li><a href="index.shtml" class="no_index" title="首页" name="mainNav">首页</a></li>
		<li><a href="page01.shtml" class="no1" title="小镇游园指南" name="mainNav">小镇游园指南</a></li>
		<li><a href="page02.shtml" class="no2" title="乐队团队模式" name="mainNav">乐队团队模式</a></li>
		<li><a href="page03.shtml" class="no3" title="贴心优化" name="mainNav">贴心优化</a></li>
		<li><a href="page04.shtml" class="no4" title="新品上市" name="mainNav">新品上市</a></li>
		<li><a href="page05.shtml" class="no5" title="最新活动" name="mainNav">最新活动</a></li>
	</ul>
